openapi: 3.0.3
info:
  title: WasaText - OpenAPI 3.0
  description: |
    This API allows sharing and receiving messages among users in WasaText.
  version: 0.0.1
tags:
  - name: Users
    description: Operations related to user profiles
  - name: Conversations
    description: Operations to manage user conversations
  - name: Messages
    description: Operations to send, forward, comment on, and delete messages
  - name: Groups
    description: Operations for managing groups, including adding members and changing group details

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      title: User
      type: object
      description: Details of a registered user
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Unique identifier of the User
        username:
          type: string
          description: Username of the User
          minLength: 3
          maxLength: 30
          pattern: "^[a-zA-Z0-9_]+$"
        photo:
          type: string
          format: uri
          pattern: "^[a-zA-Z0-9_]+$"
          description: URL to the User's profile photo
      required:
        - id
        - username

    Conversation:
      title: Conversation
      type: object
      description: Details of a conversation between users
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Unique identifier of the conversation
        lastconvo:
          type: string
          format: date-time
          pattern: "^[a-zA-Z0-9_]+$"
          description: Timestamp of the last message in the conversation
        participant:
          allOf:
            - $ref: '#/components/schemas/User'
            - description: The participant (receiver) in the conversation
      required:
        - id
        - lastconvo
        - participant

    Group:
      title: Group
      type: object
      description: Details of a group with multiple participants
      properties:
        id: 
          type: integer
          format: int64
          readOnly: true
          description: Unique identifier of the Group
        photo:
          type: string
          format: uri
          pattern: "^[a-zA-Z0-9_]+$"
          description: URL of the group's profile photo
        members:
          type: array
          items: 
            $ref: '#/components/schemas/User'
          description: List of users who are members of the group
          minItems: 1
          maxItems: 1000
      required: 
        - id
        - members

    Message:
      title: Message
      type: object
      description: Details of a message sent between users or in a group
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Unique identifier of the message
        timestamp:
          type: string
          format: date-time
          pattern: "^[a-zA-Z0-9_]+$"
          description: Timestamp when the message was sent
        content:
          oneOf:
            - type: string
              description: Text content of the message
              minLength: 1
              maxLength: 1000
              pattern: "^.*$"
            - type: string
              minLength: 3
              maxLength: 50
              format: uri
              description: URL pointing to an attached image or media file
        senderUsername:
          allOf:
            - $ref: '#/components/schemas/User'
            - description: Username of the sender
        status:
          type: string
          pattern: "^[a-zA-Z0-9_]+$"
          minLength: 3
          maxLength: 50
          enum:
            - "sent"
            - "delivered"
            - "read"
          description: Status of the message, represented by "sent," "delivered," or "read"
      required:
        - id
        - timestamp
        - content
        - senderUsername

security:
  - bearerAuth: []

paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the user
                  example: Maria
                  pattern: 'Ë†[a-zA-Z0-9]+$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    pattern: "^[a-zA-Z0-9_]+$"
                    minLength: 3
                    maxLength: 50
                    description: Identifier of the logged-in user
                    example: "abcdef012345"

  /users/me/username:
    put:
      tags:
        - Users
      summary: Set my username
      description: Updates the username of the authenticated user.
      operationId: setMyUserName
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: New username for the user
                  minLength: 3
                  maxLength: 50
                  pattern: "^[a-zA-Z0-9_]+$"
                  example: "new_username"
      responses:
        '200':
          description: Username updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    pattern: "^[a-zA-Z0-9_]+$"
                    minLength: 3
                    maxLength: 50
                    description: Success message
                    example: "Username updated successfully."
        '400':
          description: Invalid input
        '409':
          description: Username already in use

  /users/{id}/conversations:
    get:
      tags:
        - Conversations
      summary: Get my conversations
      description: Retrieves a list of all conversations involving the authenticated user.
      operationId: getMyConversations
      responses:
        '200':
          description: List of conversations retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
                minItems: 1   
                maxItems: 100 

  /users/{id}/conversations/{c_id}:
    get:
      tags:
        - Conversations
      summary: Get a specific conversation
      description: Retrieves details of a specific conversation by ID.
      operationId: getConversation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the conversation
      responses:
        '200':
          description: Conversation details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: Conversation not found

  /users/{id}/conversations/{c_id}/messages:
    get:
      tags:
        - Messages
      summary: Get messages in a conversation
      description: Retrieves all messages within a specific conversation.
      operationId: getMessagesInConversation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the conversation
      responses:
        '200':
          description: List of messages retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
                minItems: 1   
                maxItems: 100

    post:
      tags:
        - Messages
      summary: Send a message in a conversation
      description: Sends a new message within a specific conversation.
      operationId: sendMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the conversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  pattern: "^[a-zA-Z0-9_]+$"
                  minLength: 3
                  maxLength: 50
                  description: Content of the message
                status:
                  type: string
                  pattern: "^[a-zA-Z0-9_]+$"
                  minLength: 3
                  maxLength: 50
                  enum:
                    - "sent"
                    - "delivered"
                    - "read"
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /users/{id}/conversations/{c_id}/messages/{m_id}/forward:
    post:
      tags:
        - Messages
      summary: Forward a message
      description: Forwards an existing message to another conversation.
      operationId: forwardMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the message to forward
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversationId:
                  type: integer
                  description: ID of the target conversation
      responses:
        '200':
          description: Message forwarded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    pattern: "^[a-zA-Z0-9_]+$"
                    minLength: 3
                    maxLength: 50
                    description: Success message
                    example: "Message forwarded successfully."
        '404':
          description: Message not found

  /users/{id}/conversations/{c_id}/messages/{m_id}/comments:
    post:
      tags:
        - Messages
      summary: Comment on a message
      description: Adds a comment to a message.
      operationId: commentMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the message to comment on
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  pattern: "^[a-zA-Z0-9_]+$"
                  description: The comment text
                  minLength: 1
                  maxLength: 1000
      responses:
        '201':
          description: Comment added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    pattern: "^[a-zA-Z0-9_]+$"
                    description: Success message
                    example: "Comment added successfully."
        '404':
          description: Message not found

  /users/{id}/conversations/{c_id}/messages/{m_id}/comments/{commentId}:
    delete:
      tags:
        - Messages
      summary: Delete a comment from a message
      description: Deletes a specific comment from a message by message ID and comment ID.
      operationId: uncommentMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier of the message
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier of the comment to be deleted
      responses:
        '204':
          description: Comment deleted successfully
        '404':
          description: Message or comment not found

  /users/{id}/conversations/{c_id}/messages/{m_id}:
    delete:
      tags:
        - Messages
      summary: Delete a specific message
      description: Deletes a message by its unique identifier.
      operationId: deleteMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier of the message to delete
      responses:
        '204':
          description: Message deleted successfully
        '404':
          description: Message not found

  /users/{id}/conversations/{c_id}/groups/{g_id}/members:
    post:
      tags:
        - Groups
      summary: Add a user to a group
      description: Adds a user to a specified group by the group's unique identifier.
      operationId: addToGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier of the group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: Unique identifier of the user to add
      responses:
        '200':
          description: User added to the group successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    pattern: "^[a-zA-Z0-9_]+$"
                    minLength: 3
                    maxLength: 50
                    description: Success message
                    example: "User added to the group successfully."
        '404':
          description: Group or user not found

  /users/{id}/conversations/{c_id}/groups/{g_id}/leave:
    post:
      tags:
        - Groups
      summary: Leave a group
      description: Allows the authenticated user to leave a specified group.
      operationId: leaveGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier of the group
      responses:
        '200':
          description: Successfully left the group
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    pattern: "^[a-zA-Z0-9_]+$"
                    minLength: 3
                    maxLength: 50
                    description: Success message
                    example: "Successfully left the group."
        '404':
          description: Group not found

  /users/{id}/conversations/{c_id}/groups/{g_id}/name:
    put:
      tags:
        - Groups
      summary: Update group name
      description: Updates the name of a group by its unique identifier.
      operationId: setGroupName
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier of the group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: New name for the group
                  minLength: 1
                  maxLength: 100
                  pattern: "^[a-zA-Z0-9_ ]+$"
      responses:
        '200':
          description: Group name updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    pattern: "^[a-zA-Z0-9_]+$"
                    minLength: 1
                    maxLength: 100
                    description: Success message
                    example: "Group name updated successfully."
        '404':
          description: Group not found

  /users/me/photo:
    put:
      tags:
        - Users
      summary: Update user profile photo
      description: Updates the profile photo of the authenticated user.
      operationId: setMyPhoto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  pattern: "^[a-zA-Z0-9_]+$"
                  minLength: 1
                  maxLength: 100
                  format: uri
                  description: URL of the new photo for the user
      responses:
        '200':
          description: Photo updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    pattern: "^[a-zA-Z0-9_]+$"
                    minLength: 1
                    maxLength: 100
                    description: Success message
                    example: "Photo updated successfully."
        '400':
          description: Invalid input

  /users/{id}/conversations/{c_id}/groups/{g_id}/photo:
    put:
      tags:
        - Groups
      summary: Update group photo
      description: Updates the profile photo of a specified group by its unique identifier.
      operationId: setGroupPhoto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier of the group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  pattern: "^[a-zA-Z0-9_]+$"
                  minLength: 1
                  maxLength: 100
                  format: uri
                  description: URL of the new group photo
      responses:
        '200':
          description: Group photo updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    pattern: "^[a-zA-Z0-9_]+$"
                    minLength: 1
                    maxLength: 100
                    description: Success message
                    example: "Group photo updated successfully."
        '404':
          description: Group not found